version = 0.1

[default.deploy.parameters]
stack_name = "pimsleur-platform"
resolve_s3 = true
s3_prefix = "pimsleur-platform"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
