AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'API stack: Lambda functions and shared API Gateway for Pimsleur Japanese Platform'

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The stage to deploy the application to
  StackName:
    Type: String
    Description: The name of stack

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Architectures:
      - x86_64

Resources:

  # Shared API Gateway
  PimsleurApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PimsleurApi
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !ImportValue CognitoUserPoolArn
  S3UploadPresignUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      FunctionName: s3-upload-presign-url
      CodeUri: ../../src/application/handlers
      Handler: upload.handler
      Runtime: nodejs20.x
      Layers:
        - !ImportValue ConfigLayerArn
      Environment:
        Variables:
          UPLOAD_BUCKET: !ImportValue UserUploadsBucket
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue
            Fn::Sub: "${StackName}-SecurityGroupId"
        SubnetIds: !Split
          - ','
          - !ImportValue
            Fn::Sub: "${StackName}-PrivateSubnetIds"
      Events:
        Presign:
          Type: Api
          Properties:
            Path: /s3-upload-presign
            Method: GET
            RestApiId: !Ref PimsleurApi
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  PimsleurApiId:
    Description: API Gateway ID for downstream use
    Value: !Ref PimsleurApi
    Export:
      Name: PimsleurApiId