AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Storage resources for lesson audio and scripts

Parameters:
  StackName:
    Type: String
    Description: The name of stack

Resources:
  UserUploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-user-uploads"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      # CorsConfiguration:
      #   CorsRules:
      #     - AllowedOrigins:
      #         - "https://your-frontend.com" # Replace with CloudFront domain
      #       AllowedMethods:
      #         - GET
      #         - PUT
      #         - POST
      #       AllowedHeaders:
      #         - "*"
      #       ExposedHeaders:
      #         - ETag
  LessonAudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-lesson-audio"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  ScriptStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-script-storage"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

