AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Root infrastructure for Pimsleur Japanese Learning Platform

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The deployment stage

Resources:
  BackendStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../backend/infra/template.yaml
      Parameters:
        Stage: !Ref Stage
        StackName: !Ref AWS::StackName

#  FrontendStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: ../frontend/template.yaml
#      Parameters:
#        Stage: !Ref Stage
#
